// Auto-generated file - DO NOT EDIT MANUALLY
// Generated by scripts/embed-configs.ts

export const EMBEDDED_CONFIGS = {
  templates: `templates:
  debian12:
    id: 9000
    name: "Debian 12"
    description: "Debian 12 Bookworm CloudInit"
    arch: "amd64"
    default_user: "vmuser"
    storage: "pve-a"  

defaults:
  cores: 2
  memory: 2048
  disk_size: "10G"
  storage: "pve-a" 
  network:
    bridge: "vmbr0"
    model: "virtio"
    vlan: 3604
    speed: 125`,
  envExample: `# Server Configuration
LOG_LEVEL=info
LOG_COMMANDS=false
PORT=4000
HOST=0.0.0.0

# Database Configuration
MONGODB_URI=mongodb://localhost:27017/proxmox-daemon

# API Security
API_TOKEN=your-secure-api-token-here
# Optional: Multiple tokens separated by commas
# API_TOKENS=token1,token2,token3

# Development/Production Environment
NODE_ENV=development

# Example of a secure API token (32 characters)
# You can generate one using: bun scripts/generate-token
# API_TOKEN=`,
} as const;

export const CONFIG_FILES = {
  'templates.yaml': EMBEDDED_CONFIGS.templates,
  '.env.example': EMBEDDED_CONFIGS.envExample,
} as const;

/**
 * Check if running from binary (no config directory available)
 */
export function isRunningFromBinary(): boolean {
  const fs = require('fs');
  const path = require('path');
  return !fs.existsSync(path.join(process.cwd(), 'config', 'templates.yaml'));
}
